# WARNING: 
# The env variables used in this file (e.g. WASM_PATH_LOCAL) can only 
# be read by a file named ".env". This is standard Docker behaviour.

# 1. Configure ./.env file
# 2. docker-compose -f docker-compose.base.yml -f docker-compose.yml up --build

version: '3.7'

services:
  swam_server:
    build: ./fuzzing-server
    expose:
      - ${SWAM_SOCKET_PORT:?err}

  afl_interface:
    build: ./fuzzing-client-afl
